shopping_list = []
shopping_list.append("soap")
print(shopping_list)
shopping_list.append("ice-cream")
print(shopping_list)
shopping_list.append("choclate")
print(shopping_list)
shopping_list.append("clothes")
print(shopping_list)
shopping_list.append("fruits")
print(shopping_list)
shopping_list.append("vegetables")
print(shopping_list)
shopping_list.append("snacks")
print(shopping_list)
shopping_list.append("eggs")
print(shopping_list)
shopping_list.append("computer")
print(shopping_list)
shopping_list.append("bag")
print(shopping_list)
print("shopping_list has {} items".format(len(shopping_list)))

print(shopping_list[4])